version: '3'

services:
  postgres:
    build: ./docker/postgres
    volumes:
      - data_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "mega"
    ports:
      - "5432:5432"
  monitor:
    image: 3megawatt/dev-recruiting-challenge-monitor
    ports:
      - "5000:5000"
volumes:
  data_postgres:
    driver: local