version: '3'

services:
  postgres:
    build: ./docker/postgres
    volumes:
      - data_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "mega"
    ports:
      - "5432:5432"
  monitor:
    image: 3megawatt/dev-recruiting-challenge-monitor
    ports:
      - "5000:5000"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=mega
      - RABBITMQ_DEFAULT_PASS=mega
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
      - "8000:8000"
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    environment:
      DOCKER_IP: "postgres"
    links:
      - postgres
  worker:
    build: .
    command: pipenv run celery -A megawatt worker -l info
  beat:
    build: .
    command: pipenv run celery -A megawatt beat -l info

volumes:
  data_postgres:
    driver: local