# Generated by Django 2.2.9 on 2020-01-27 01:03

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200125_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='monitoring_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 1, 3, 25, 946012), verbose_name='Monitoring date'),
        ),
    ]
