# Generated by Django 2.2.9 on 2020-01-27 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200127_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.AlterField(
            model_name='report',
            name='monitoring_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 1, 36, 32, 709436), verbose_name='Monitoring date'),
        ),
    ]
